backend:
  name: github
  repo: sumuzhi/sumuzhi.github.io
  branch: main
  base_url: https://sumuzhi.github.io

media_folder: public/images
public_folder: /images

collections:
  - name: blog
    label: Blog Posts
    folder: content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime, format: YYYY-MM-DD }
      - { name: tags, label: Tags, widget: list, default: ["misc"] }
      - { name: excerpt, label: Excerpt, widget: text }
      - { name: body, label: Body, widget: markdown }
